version: '3'

networks:
  kafka-net:
    external: true

services:
  aggregator:
    build:
      context: service
      dockerfile: Dockerfile
    environment:
      - KAFKA_SERVER=kafka1:9092
      - SCHEMA_SERVER=http://schema-registry:8081
    networks:
      - kafka-net